### ISSUE TITLE
rg takes up all memory (>10GB)

### ISSUE THREAD

**Issue by albertz** [microsoft/vscode-ripgrep#11]
## Environment data

-   VS Code Version:
Version: 1.44.0
Commit: 2aae1f26c72891c399f860409176fe435a154b13
Date: 2020-04-08T08:23:56.137Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 17.7.0
-   Extension version (available under the Extensions sidebar): 2020.3.71659
-   OS and version: Desktop is MacOSX 10.13, SSH server is Linux (Ubuntu 16).
-   Python version (& distribution if applicable, e.g. Anaconda): CPython 3.6.3
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): None
-   Relevant/affected Python packages and their versions: None
-   Relevant/affected Python-related VS Code extensions and their versions: `ms-python.python`
-   Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info #3977): Jedi is enabled.
-   Value of the `python.languageServer` setting: Microsoft

[Via](https://github.com/microsoft/vscode/issues/95201) and [via](https://github.com/microsoft/vscode-python/issues/11173).

## Expected behaviour

It should run without crashing the system due to running out-of-memory (OOM).

## Actual behaviour

The `rg` process takes a lot of memory (>10GB). In the extreme case, it crashes the whole system.

## Steps to reproduce:

(Start VSCode with SSH extension. This is probably not relevant. This is just needed in my case because the project directory is on the Linux server.)

Open a very big project directory (containing several 100GB, many thousand files, slow to access via NFS).

See `ps axu` on the Linux SSH server, and search for the `rg` process by VSCode:
```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
zeyer    14685  117 53.7 8244360 8231756 ?     Sl   11:12  13:09 /u/zeyer/.vscode-server/bin/0ba0ca52957102ca3527cf479571617f0de6ed50/node_modules/vscode-ripgrep/bin/rg --files --hidden --case-sensitive -g **/*.ipynb -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store -g !**/__pycache__ -g !**/*.pyc --no-ignore --follow --no-config --no-ignore-global
zeyer    20113 87.3 12.8 1978088 1965448 ?     Sl   11:30   4:42 /u/zeyer/.vscode-server/bin/2aae1f26c72891c399f860409176fe435a154b13/node_modules/vscode-ripgrep/bin/rg --files --hidden --case-sensitive -g **/*.ipynb -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store -g !**/__pycache__ -g !**/*.pyc --no-ignore --follow --no-config --no-ignore-global
```
The `cwd` of that process is a VSCode setup, which is the very big project directory. Many of the files are behind some symlinks, but I partly want to follow symlinks. (I'm not sure how to selectively disable to not follow some of the symlinks.)

I think the issue is that the directory is just very big.

I happened already multiple times that the Linux server became unresponsive because all memory was occupied, and luckily the Linux OOM killer killed `rg` and the system recovered a while later. This is what I see in `dmesg -T`:

```
[Tue Apr 14 11:14:15 2020] [ pid ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
...
[Tue Apr 14 11:14:15 2020] [27303]  2574 27303  2550868  2546981 20484096        0             0 rg
...
[Tue Apr 14 11:14:15 2020] Out of memory: Kill process 27303 (rg) score 528 or sacrifice child
[Tue Apr 14 11:14:15 2020] Killed process 27303 (rg) total-vm:10203472kB, anon-rss:10187924kB, file-rss:0kB, shmem-rss:0kB
[Tue Apr 14 11:14:15 2020] oom_reaper: reaped process 27303 (rg), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

In any case, this should never happen (crashing my whole system because OOM), even if the user opens a immensely huge directory (or let's say an infinite big virtual FUSE directory).

I tried to have this in the `.vscode/settings.json` but this does not seem to have an effect:
```
{
    // ...

    "search.exclude": {
        "**/data-*": true,  // there are huge directories behind this
        "logs-*": true,
        // and some more...
    },
}
```

**Comment by albertz** [comment]
The workaround I tried with `"search.exclude"` does not work. Maybe there is another `exclude` option? From the code ([nativeEditorProvider.ts](https://github.com/microsoft/vscode-python/blob/bd8d32bccbf9b459981db18c837ee68414335cf4/src/client/datascience/interactive-ipynb/nativeEditorProvider.ts#L91)) I'm not sure what `exclude` will be relevant. I think this would be anyway good to have (such an `exclude` option, which will always be respected by ripgrep searched, i.e. all `workspace.findFiles`calls).

**Comment by madhavajay** [comment]
Im seeing a similar issue:
https://github.com/BurntSushi/ripgrep/issues/1640#event-3527395604

**Comment by albertz** [comment]
@madhavajay Note that [this](https://github.com/microsoft/vscode/issues/48674) discusses how to be able to at least workaround this issue by disabling the search (`rg`) on problematic sub-directories. However, it seems to not be finished yet.

**Comment by madhavajay** [comment]
@albertz, yes sorry, all I did was use the extension search box to filter extensions that I have installed by keywords. The Author of rg seems to think its not in the scope of the main project so I figured I would report it somewhere and this looks related. If you think its not I can move it.

**Comment by albertz** [comment]
It's definitely related. But in my opinion, the two possible things to fix are:

* In `rg` itself, such that sth like this can never happen. But the author of `rg` does not want this.
* A better API in VSCode to define what files/directories to ignore. This would be a workaround. This is the issue I linked.
  Once this is finished, it also needs to be adopted to the VSCode-ripgrep extension. This is this issue here.

**Comment by roblourens** [comment]
Sorry for the slow response.

- First, please try with VS Code Insiders, I have upgraded the ripgrep version and you might see better perf.
- `files.exclude` should be applied for this extension search, not `search.exclude`
- This is just the repo for the module that downloads the rg binary for vscode. I'm going to close this but if we need to continue the discussion, we can open an issue in the vscode repo

> A better API in VSCode to define what files/directories to ignore.

Yes, there are issues for this (looks like you've found one)
