### ISSUE TITLE
How to use the system ripgrep?

### ISSUE THREAD

**Issue by colemickens** [microsoft/vscode-ripgrep#16]
Please give users a way to use the system ripgrep.

**Comment by roblourens** [comment]
Why? We might make assumptions about the ripgrep version, so we want to be able to control which version is used.

**Comment by oleastre** [comment]
Using the system ripgrep could just solve many download issues in the postinstall script. 
Ensuring a minimal version of ripgrep is compiled is as easy as parsing the first line of `rg --version` output.
And some users are more kind to trust locally compiled binaries than downloading pre build binaries.

**Comment by roblourens** [comment]
I'm not interested in doing this for vscode.

**Comment by oleastre** [comment]
@roblourens Would you be interested if we come with a pull request that implement the required changes ?
This could help other projects that reuse this implementation.

**Comment by roblourens** [comment]
This is a pretty simple project with a singular purpose, and I think it might be more appropriate to have a different project for what you are looking for.

**Comment by colemickens** [comment]
By the way, I did notice this: https://github.com/microsoft/vscode-ripgrep/blob/master/lib/postinstall.js#L51. Just in case other people have requirements that make "arbitrarily downloading random binaries during the build process" untenable.
