### ISSUE TITLE
Process abnormal

### ISSUE THREAD

**Issue by robinv8** [microsoft/vscode-ripgrep#23]
![image](https://user-images.githubusercontent.com/12277531/128475744-c91b9ce7-6ffe-48bf-afda-bb04d3e59a6d.png)

system: macos 12.0 beta

**Comment by roblourens** [comment]
This process is spawned to do a search, one per workspace folder. Searches can be started by the user or by extensions. 
Please see more info here: https://github.com/microsoft/vscode/wiki/Search-Issues
