### ISSUE TITLE
download.js fails to properly handle https proxies

### ISSUE THREAD

**Issue by alexmurray** [microsoft/vscode-ripgrep#26]
When trying to install vscode-ripgrep behind a https proxy, it fails with:

```
error /build/vscode-json-languageserver/parts/vscode-json-languageserver/build/node_modules/vscode-ripgrep: Command failed.
Exit code: 1
Command: node ./lib/postinstall.js
Arguments: 
Directory: /build/vscode-json-languageserver/parts/vscode-json-languageserver/build/node_modules/vscode-ripgrep
Output:
Finding release for v13.0.0-2
GET https://api.github.com/repos/microsoft/ripgrep-prebuilt/releases/tags/v13.0.0-2
Deleting invalid download cache
Downloading ripgrep failed: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
    at new NodeError (node:internal/errors:371:5)
    at new ClientRequest (node:_http_client:158:11)
    at request (node:https:353:10)
    at Object.get (node:https:387:15)
    at /build/vscode-json-languageserver/parts/vscode-json-languageserver/build/node_modules/vscode-ripgrep/lib/download.js:141:15
    at new Promise (<anonymous>)
    at get (/build/vscode-json-languageserver/parts/vscode-json-languageserver/build/node_modules/vscode-ripgrep/lib/download.js:135:12)
    at getAssetFromGithubApi (/build/vscode-json-languageserver/parts/vscode-json-languageserver/build/node_modules/vscode-ripgrep/lib/download.js:190:27)
    at async module.exports (/build/vscode-json-languageserver/parts/vscode-json-languageserver/build/node_modules/vscode-ripgrep/lib/download.js:298:9)
    at async main (/build/vscode-json-languageserver/parts/vscode-json-languageserver/build/node_modules/vscode-ripgrep/lib/postinstall.js:83:9)
```

This is similar to https://github.com/npm/cli/issues/2003 and other issues and likely would be fixed by updating package.json to use `https-proxy-agent` `5.0.0` or similar.

**Comment by ruimarques** [comment]
Issue seems to be if you're using the current node LTS 16.13.x

Seems to work with node 14.17.x

**Comment by roblourens** [comment]
@weartist is still seeing the original issue. https://github.com/microsoft/ripgrep-prebuilt/issues/17

I don't know what the problem would be and am not able to reproduce this. @weartist it sounds like you can downgrade node in the meantime at least.

**Comment by lawvs** [comment]
the legacy dependency `vscode-ripgrep` still in vscode due to `@vscode/telemetry-extractor@1.9.5`.

this problem will be solved after vscode upgrades `@vscode/telemetry-extractor@1.9.5` to `@vscode/telemetry-extractor@1.9.6`.

Here is a workaround if you don't need a proxy. 

```
unset http_proxy; unset https_proxy; unset all_proxy;
```

---

```
> yarn why vscode-ripgrep                                                                          

[1/4] 🤔  Why do we have the module "vscode-ripgrep"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "vscode-ripgrep@1.13.2"
info Reasons this module exists
   - "@vscode#telemetry-extractor" depends on it
   - Hoisted from "@vscode#telemetry-extractor#vscode-ripgrep"
```

**Comment by roblourens** [comment]
Oh, thanks. FYI @lramos15

**Comment by RSzyh** [comment]
When I **use the proxy** to `yarn install` in vscode repo, it still fails. Some info:

@vscode/ripgrep: `1.14.2`
node: `v16.15.1`

How to make it work by using proxy?

Thanks.

**Comment by RSzyh** [comment]
When I **use the proxy** to `yarn install` in vscode repo, it still fails. Some info:

@vscode/ripgrep: `1.14.2`
node: `v16.15.1`

How to make it work by using proxy?

Thanks.

**Comment by quanzhuo** [comment]
> When I **use the proxy** to `yarn install` in vscode repo, it still fails. Some info:
> 
> @vscode/ripgrep: `1.14.2` node: `v16.15.1`
> 
> How to make it work by using proxy?
> 
> Thanks.

same question

**Comment by aadisriram** [comment]
I have a workaround that i've been using for this:

1. Clone ripgrep locally: git clone git@github.com:microsoft/vscode-ripgrep ~/vscode-ripgrep
2. run yarn in that folder (this seems to work even behind proxy)
3. cp bin/rg <vscode-repo-path>/node_modules/@vscode/ripgrep
4. run yarn in your vscode repo path again

This is not ideal but has unblocked me!

**Comment by xueqianz** [comment]
> I have a workaround that i've been using for this:
> 
> ```
> 1. Clone ripgrep locally: git clone git@github.com:microsoft/vscode-ripgrep ~/vscode-ripgrep
> 2. run yarn in that folder (this seems to work even behind proxy)
> 3. cp bin/rg ~/vscode-repo-path/node_modules/@vscode/ripgrep
> 4. run yarn in your vscode repo path again
> ```
> 
> This is not ideal but has unblocked me! The reason this works is because its the postInstall script in ripgrep that is failing, once you put the download in the bin folder the postInstall script notices it already exists and ignores the download bit.

Yes, it unblocked me too! For the perspective of solving the problem, it indeed is ideal~ :)

**Comment by yuhorun** [comment]
> When I **use the proxy** to `yarn install` in vscode repo, it still fails. Some info:
> 
> @vscode/ripgrep: `1.14.2` node: `v16.15.1`
> 
> How to make it work by using proxy?
> 
> Thanks.

set yarn proxy:
http-proxy=http://127.0.0.1:7890
https-proxy=http://127.0.0.1:7890  (not  https://127.0.0.1:7890)
