### ISSUE TITLE
Post Install script causes issue when running on build server

### ISSUE THREAD

**Issue by arunswarnam** [microsoft/vscode-ripgrep#27]
Hi! 
We are trying to build an app that depends on this package on our build server (no internet egress) and we are facing issue probably because of this : https://github.com/microsoft/vscode-ripgrep/blob/main/lib/download.js#L190

```
verbose 254.0814148 Error: /root/bld/input_build/node_modules/vscode-ripgrep: Command failed.
Exit code: 1
Command: node ./lib/postinstall.js
Arguments: 
Directory: /root/bld/input_build/node_modules/vscode-ripgrep
Output:
Finding release for v13.0.0-2
GET https://api.github.com/repos/microsoft/ripgrep-prebuilt/releases/tags/v13.0.0-2
events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 
```
Is there a workaround to avoid accessing  https://api.github.com post install?

**Comment by roblourens** [comment]
This package downloads ripgrep when it is installed, that is the purpose of the package.
