### ISSUE TITLE
tags v13.0.0-5 doesn't exists

### ISSUE THREAD

**Issue by lengthmin** [microsoft/vscode-ripgrep#29]
![image](https://user-images.githubusercontent.com/13938334/147627517-931cbae4-866a-4f58-aee3-8b3bc6e813d5.png)

**Comment by impriyanshub** [comment]
I am facing the same issue.

**Comment by roblourens** [comment]
The 1.13.1 release is broken, 1.13.0 will work. I will publish a new one to make sure the latest is good.

**Comment by roblourens** [comment]
Published 1.13.2, if they are pulling in the latest patch release that should help.
