### ISSUE TITLE
Re-publish vscode-ripgrep to NPM

### ISSUE THREAD

**Issue by SBell6hf** [microsoft/vscode-ripgrep#31]
Re-publish `vscode-ripgrep` to NPM in order to have newer version installed when `yarn install`ing VSCode.

https://github.com/microsoft/vscode-ripgrep/pull/30#issuecomment-1057013146

**Comment by roblourens** [comment]
vscode-ripgrep is deprecated, please use `@vscode/ripgrep`

**Comment by SBell6hf** [comment]
Sorry, I mean Re-publish `@vscode/ripgrep`

**Comment by SBell6hf** [comment]
https://github.com/microsoft/vscode-ripgrep/issues/26#issuecomment-1029373044
> @weartist is still seeing the original issue. [microsoft/ripgrep-prebuilt#17](https://github.com/microsoft/ripgrep-prebuilt/issues/17)
> 
> I don't know what the problem would be and am not able to reproduce this. @weartist it sounds like you can downgrade node in the meantime at least.

The issue persists because most people install the old version of `@vscode/ripgrep` as a dependency of VSCode from NPM.

**Comment by roblourens** [comment]
I bumped the version number in vscode, I guess this is what you mean.
