### ISSUE TITLE
GLIBC 2.18 requirement causes incompatibility with CentOS 7

### ISSUE THREAD

**Issue by sfc-gh-pbennes** [microsoft/vscode-ripgrep#34]
Greetings!

It appears that the Linux build of ripgrep for VSCode is happening in an environment with GLIBC 2.18. This results in a binary incompatible with operating systems with a lower GLIBC version. CentOS 7 ships with GLIBC 2.17 and is one such incompatible OS.

This causes issues with vscode features that rely on ripgrep funcitonality: https://github.com/microsoft/vscode-remote-release/issues/6930. Specifically https://github.com/microsoft/vscode-remote-release/issues/6930#issuecomment-1216968883.

Can the build be moved to an environment with a GLIBC version 2.17 or lower to support CentOS 7?

**Comment by chrmarti** [comment]
@roblourens https://stackoverflow.com/a/47239631/7857763 suggests to use an older Rust toolchain that only supports GLIBC 2.17. (We currently list GLIBC 2.17 and CentOS 7 as supported in https://code.visualstudio.com/docs/supporting/requirements.)

**Comment by mshijie** [comment]
I was wondering if there have been any developments on this issue.
