### ISSUE TITLE
Using existing ripgrep of the version required

### ISSUE THREAD

**Issue by ohhmm** [microsoft/vscode-ripgrep#60]
How about using existing ripgrep accessible in path when its version matches?

**Comment by roblourens** [comment]
Why?

**Comment by ohhmm** [comment]
To omit unnecessary delays during project loading

**Comment by roblourens** [comment]
That's not really the goal of this project, since it's designed for scenarios like vscode where we download ripgrep at build time then bundle it with vscode.

**Comment by ohhmm** [comment]
No, I can see the downloading message while entering docker environment
